language: sh
arch:
  - amd64
  - ppc64le
script: make test
os:
  - linux
  - osx
notifications:
  slack:
    rooms:
      secure: 00NNL6SphnK5pCAjqRz9GzFICGb0IKfcZIEw94f6yGcS+uJXmacTnHGr084irxYuIiOSzk5Yrz7ai6HEUgYIubCmHNnVBuA4iuXQ/kbcH73fC8G4fZh+aphYXUvBRe3rOaUszAxXlmSJ0z6bQ9DqRZsixRYBLPVo55elI9W13RAfZ9ctvGlmyw8plo+jlww7xgBRoTB381YKGeGX1sEZkDBcHgOTGyIaHWsiAwUaVOWkRE5MgsIepZs0aTRsuZGwIzuZ5V5RCJx5ad1qSD8qR/kBCY6lDLr6f38X3/W9AGoQbyhG/rPjzL0xentYx3jRpsUrS8F+sxz2b0Lllv0zy5lT/E5KgemNDLa2C3s9EMXoWc0jA7QqTbDlbFYPnOueQXdn107IxX60WJiu2w3XEnrZJ5CMC1C+YLXV2gxmfTdmKtLirc+4dlXHI20Ydw/eji8vIA+HKu+7BZyqv6CDTrj2edXsQeCh2sWjADqqNvJ3K+JiwDtojNBjs0t/zoKHeI9ANFrtG10MyrsAeP++l79e/ma0x1DF/oRzHibpLaMtOSZ3624NfXEnw54MJ29bTLzNoPFZcy8Wo9f72z3oqv6tPjYLK1KHjPLZu9YvvsN8UX/oIA2Yc4an9BGFyhL5s+9PEu4IYqmEIjhxVjlZbasnBvyN8FUUbom4+PQRr+Q=
